In [1]:
from minerva.data.data_modules.har_reyes_16 import ReyesModule

In [2]:
batch_size = 42
percentage = 1.0
data_path = "/workspaces/HIAAC-KR-Dev-Container/shared_data/reyes_2016_datasets/uci-6-9x128-50Hz/artigo/"
full42_dm = ReyesModule(data_path, batch_size, percentage)

# show batches of training data
i = 0
print("There are", len(full42_dm.train_dataloader()), "batches in the training set.")
for batch in full42_dm.train_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 2 == 0:
        break

# show batches of val data
print("There are", len(full42_dm.val_dataloader()), "batches in the val set.")
for batch in full42_dm.val_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 2 == 0:
        break

# show batches of test data
print("There are", len(full42_dm.test_dataloader()), "batches in the test set.")
for batch in full42_dm.test_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 2 == 0:
        break

There are 175 batches in the training set.
tensor([3, 1, 2, 0, 0, 5, 4, 3, 4, 2, 0, 1, 3, 5, 4, 0, 2, 4, 5, 5, 4, 2, 1, 1,
        2, 3, 5, 5, 4, 3, 3, 2, 0, 3, 4, 3, 0, 4, 5, 3, 3, 0],
       dtype=torch.int32) shape: torch.Size([42])

tensor([1, 2, 1, 1, 4, 3, 4, 0, 4, 2, 1, 4, 3, 5, 4, 5, 4, 4, 2, 2, 3, 2, 3, 5,
        4, 5, 0, 3, 1, 5, 3, 2, 2, 2, 0, 4, 1, 0, 2, 4, 2, 4],
       dtype=torch.int32) shape: torch.Size([42])

There are 175 batches in the val set.
tensor([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       dtype=torch.int32) shape: torch.Size([42])

tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0],
       dtype=torch.int32) shape: torch.Size([42])

There are 70 batches in the test set.
tensor([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4,

In [3]:
batch_size = 7
percentage = 0.001
data_path = "/workspaces/HIAAC-KR-Dev-Container/shared_data/reyes_2016_datasets/uci-6-9x128-50Hz/artigo/"
full42_dm = ReyesModule(data_path, batch_size, percentage)

# show batches of training data
i = 0
print("There are", len(full42_dm.train_dataloader()), "batches in the training set.")
for batch in full42_dm.train_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 3 == 0:
        break

# show batches of val data
print("There are", len(full42_dm.val_dataloader()), "batches in the val set.")
for batch in full42_dm.val_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 3 == 0:
        break

# show batches of test data
print("There are", len(full42_dm.test_dataloader()), "batches in the test set.")
for batch in full42_dm.test_dataloader():
    i+=1
    print(batch[1], f"shape: {batch[1].shape}\n")
    if i % 3 == 0:
        break

There are 0 batches in the training set.
There are 0 batches in the val set.
There are 421 batches in the test set.
tensor([4, 4, 4, 4, 4, 4, 4], dtype=torch.int32) shape: torch.Size([7])

tensor([4, 4, 4, 4, 4, 4, 4], dtype=torch.int32) shape: torch.Size([7])

tensor([4, 4, 4, 4, 4, 4, 4], dtype=torch.int32) shape: torch.Size([7])

